### PR TITLE
Updating French localization

### PR DESCRIPTION
**Pull request by Atnode**
Updating the French README and language file.

### CODE REVIEW

**Comment by ercanersoy** [comment]
Can you control date format on French README, please?

**Comment by Atnode** [comment]
Oops, I forgot the first date....

**Comment by ercanersoy** [comment]
Can you control format of all dates on French README, please?

**Comment by Atnode** [comment]
In fact, I wasn't wrong in my first commit.
In France, we use the DD/MM/YY format.

**Comment by ercanersoy** [comment]
Thanks for interesting.

**Pull request merged**
